[package]
name = "lexer"
version = "0.0.0"
edition = "2021"

[dependencies]
bytes-str = "0.2.7"
indexmap = "2.12.1"
swc_common = { version = "18.0.1" }
swc_ecmascript = { version = "49.0.0", features = ["parser", "visit"] }
